export const FETCH_POKEMON_LIST_START = "FETCH_POKEMON_LIST_START";
export const FETCH_POKEMON_LIST_SUCCESS = "FETCH_POKEMON_LIST_SUCCESS";
export const FETCH_POKEMON_LIST_ERROR = "FETCH_POKEMON_LIST_ERROR";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

